### ISSUE TITLE
Unable to load save file

### ISSUE THREAD

**Issue by virsia** [Exiua/LTSaveEd#30]
Unable to open save file after reaching certain file size

**To Reproduce**
1. have big enough save file
2. open file in attemp to use Git version of the editor
3. and it fail to load.

another bug is:
need to reload page after using because it always come back as error if using it to reload after editing

**Comment by Exiua** [comment]
If your second bug refers to the issue that occurs when loading a new save after having a save already loaded, that should be fixed in the current version ([v2.3.3](https://exiua.github.io/LTSaveEd/)) of the save editor. For your first bug, could you post a sample save file where this issue occurs?

**Comment by WBSpitfire** [comment]
Also having this issue. Attached is a save file from v0.4.9. The same save works in the older Java release. Had to ZIP to upload.

[s32.xml.zip](https://github.com/Exiua/LTSaveEd/files/14235494/s32.xml.zip)

**Comment by Exiua** [comment]
@WBSpitfire Your issue was not due to save file size, but because the used condom item does not have a name attribute when, afaik, every other item does. This missing attribute caused the save editor to crash internally. This bug should be fixed in the latest version ([v2.4.1](https://exiua.github.io/LTSaveEd/)) of the save editor.
